config/routes.rb
KwJesusdemari::Application.routes.draw do

  get "treatment/index"

  get "group/index"
  
  resources :news
  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  resources :products do
    member do
      get "show_subcategory"
      get "show_product"
      get "show_productspec"
      get "show_subcategoryspec"
    end
  end
  resources :sustainability
  resources :budgets
  
  
  namespace(:admin){
    resources :categories do
      resources :subcategories do
        resources :products do
	  resources :product_images 
	end
      end
    end
    resources :notices
    resources :static_contents
    resources(:sections){
		resources :banners
    }
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  root :to => "home#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  











end

app/models/banner.rb
class Banner < ActiveRecord::Base
  #attr_accessible :title, :link, :section_id, :published, :active
  belongs_to :section
  has_attached_file:image, :styles =>{:thumb => "50x50#",:rotative => "950x410#",:partner => "378x295#",:partner_secondary => "378x160#",:group => "950x572#"}
end

app/models/budget.rb
class Budget < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  #attr_accessible :title, :description
has_many :subcategories
has_attached_file:logo, :styles =>{:thumb => "50x50#",:logo => "291x138#"}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name, :email, :phone, :city, :state, :message
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  validates_presence_of :title, :summary, :body
  has_attached_file:image, :styles =>{:thumb => "50x50#",:home => "150x100#",:index => "172x133#",:show => "172x133#"}
end

app/models/product.rb
class Product < ActiveRecord::Base
  #default_scope where(:active => true)
  #attr_accessible :summary, :body, :link, :active, :published
  belongs_to :subcategory
  has_many :product_images
  has_attached_file:logo, :styles =>{:thumb => "50x50>",:logo => "291x138>"}
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image, :styles => { :medium => "298x373>", :thumb => "150x150>"}
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/section.rb
class Section < ActiveRecord::Base
  #attr_accessible :title
  has_many :banners
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  #attr_accessible :category_id, :title
  belongs_to :category
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
layout "inadmin"
before_filter :load_subcategorie

uses_tiny_mce :options => {
                            :theme => 'advanced',
                            :theme_advanced_resizing => true,
                            :theme_advanced_resize_horizontal => false,
                            :plugins => %w{ table fullscreen }
                          }

  def index
    @products = @subcategory.products.all
  end

  def show
    @product = @subcategory.products.find(params[:id])
  end

  def new
    @product = @subcategory.products.new(:active => true)
  end

  def create
    @product = @subcategory.products.new(params[:product])
    if @product.save
      redirect_to admin_category_subcategory_product_path(@category,@subcategory,@product), :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = @subcategory.products.find(params[:id])
  end

  def update
    @product = @subcategory.products.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to admin_category_subcategory_product_path(@category,@subcategory,@product), :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = @subcategory.products.find(params[:id])
    @product.destroy
    redirect_to admin_category_subcategory_products_path(@category,@subcategory), :notice => "Successfully destroyed product."
  end
  
  def load_subcategorie
  @category = Category.find(params[:category_id])
  @subcategory = Subcategory.find(params[:subcategory_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all # Utilizado para trazer o Menu de Categorias
  end
  
  def show_subcategory # Carrega as variaveis com o ID da Categoria e Subcategoria
    @category = Category.find_by_id(params[:id])
    @subcategories = @category.subcategories
  end
  
  def show_product
    @subcategories = Subcategory.find_by_id(params[:id])
    @products = @subcategories.products
    @product = Product.find_by_id(params[:id])
    @subcategory = @subcategories
  end
  
  def show_productspec
    @products = Product.find_by_id(params[:id])
    @product = @products
    @product_images = @product.product_images.all
  end

  def show
    @product = Product.find(params[:id])
    @category_id = Category.find_by_id(params[:id])
    @subcategory_id = Subcategory.find_by_id(params[:id])
    @product_id = Product.find_by_id(params[:id])
    if !@category_id.blank?
      render :index
    else
      redirect_to products_path
    end
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/treatment_helper.rb
module TreatmentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<%= form_for ([:admin,@category,@subcategory,@product], :html => { :multipart => :true }) do |f| %>
  <%= f.error_messages %>
  <p>
  <p>
    <%= f.label :title, "Título" %><br />
    <%= f.text_field :title, :placeholder => "Título", :class => "twelve columns"  %>
  </p>
    <%= f.label :summary, "Descrição" %><br />
    <%= f.text_field :summary, :placeholder => "Resumo", :class => "twelve columns"  %>
  </p>
  <p>
    <%= f.label :body, "Especificações" %><br />
    <%= f.text_area :body, :placeholder => "Descrição", :class => "twelve columns mceEditor"  %>
  </p>
  <p>
    <%= f.label :logo, "Imagem" %>
    <%= f.file_field :logo %>
  </p>
  <%if @product.logo.file?%>

  <p> 

  <%= image_tag(@product.logo.url(:thumb)) %>

  </p>
  <% end %>
  <p>
    <%= f.label :link %><br />
    <%= f.text_field :link, :placeholder => "Link", :class => "twelve columns"  %>
  </p>
  <p>
    <%= f.label :Publicado %><br />
    <%= f.check_box :published %>
  </p>
  <p>
    <%= f.label :Ativo %><br />
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit "Salvar", :class => "button" %></p>
<% end %>

app/views/admin/products/edit.html.erb
<% title "Editar Produto" %>

<%= render 'form' %>

<p>
  <%= link_to "Ver", admin_category_subcategory_product_path(@category,@subcategory,@product), :class => "secondary small button" %> |
  <%= link_to "Ver Todos", admin_category_subcategory_products_path(@category,@subcategory), :class => "secondary small button" %>
</p>

app/views/admin/products/index.html.erb
<% title "Produtos" %>
<h1>Produtos</h1>
<table class="twelve columns">
  <tr>
    <th>Resumo</th>
    <th>Link</th>
    <th>Publicado</th>
    <th>Ativo</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.link %></td>
      <td><%= product.published %></td>
      <td><%= product.active %></td>
      <td><%= link_to "Visualizar", admin_category_subcategory_product_path(@category,@subcategory,product), :class => "secondary small button" %></td>
      <td><%= link_to "Editar", edit_admin_category_subcategory_product_path(@category,@subcategory,product), :class => "secondary small button" %></td>
      <td><%= link_to "Imagens das especificações", admin_category_subcategory_product_product_images_path(@category,@subcategory,product), :class => "secondary small button" %></td>
      <td><%= link_to "Deletar", admin_category_subcategory_product_path(@category,@subcategory,product), :class => "secondary small button", :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "+ Produto", new_admin_category_subcategory_product_path(@category,@subcategory,product), :class => "button" %></p>
<p><%= link_to "Voltar", admin_category_subcategories_path(@category,@subcategory), :class => "button" %></p>

app/views/admin/products/new.html.erb
<% title "Novo Produto" %>

<%= render 'form' %>

<p><%= link_to "Voltar a Lista", admin_category_subcategory_products_path, :class => "secondary small button"  %></p>

app/views/admin/products/show.html.erb
<% title "Produto" %>

<p>
  <strong>título:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Resumo:</strong>
  <%= @product.summary %>
</p>
<p>
  <strong>Descrição:</strong>
  <%= raw(@product.body) %>
</p>
<p>
  <strong>Link:</strong>
  <%= @product.link %>
</p>

<p>
  <%= link_to "Editar", edit_admin_category_subcategory_product_path(@category,@subcategory,@product), :class => "secondary small button" %> |
  <%= link_to "Deletar", admin_category_subcategory_product_path(@category,@subcategory,@product), :class => "secondary small button", :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Ver Todos", admin_category_subcategory_products_path(@category,@subcategory), :class => "secondary small button" %>
</p>

app/views/products/_product.html.erb
<div class="field_item_category">
      	<% @products.each do |product| %>
    <div class="item_category" id="button_<%=product.id.to_s%>">
      <%=link_to product.title, show_productspec_product_path(product.id), :remote => true, :class => "text_category", :id => "prod_"+product.id.to_s%>
    </div>
    <% end %>
      </div>

app/views/products/_productimagespec.html.erb
  <% @product_images.each do |image| %>
  <div class="small-4 columns content_desk img_prod_space">
    <%= image_tag(image.image("medium"), :title => image.title)%>
    </div> 
  <% end %>

app/views/products/_productspec.html.erb
<div class="item_info_right">
<div class="item_image">
<% if @product.logo.file?%>
<%= image_tag(@product.logo.url("logo"))%>
<% end %>
</div>
<div class="item_text">
<p><%= @product.summary%></p>
</div>
</div>

app/views/products/_subcategory.html.erb
<% @subcategories.each do |subcategory|%>
  <%=link_to subcategory.title, show_product_product_path(subcategory.id), :remote => true, :id => "sub_"+subcategory.id.to_s, :class=>"sub_item_a" %>
<% end %>

app/views/products/_subcategoryspec.html.erb
<%= raw(@product.body)%>

app/views/products/index.html.erb
<% content_for :head do%>
<%= stylesheet_link_tag 'produtos'%>
<% end %>
<div class="row">
<div class="small-12 columns content_mobile">
        <div class="bread_crumb_field">
            <ul>
                <img src="/images/img_arrow_left.png" class="bc_arrow_left">
                <li class="bc_text_1">
                    ...Anéis de Concreto &gt; 
                </li>
                <li class="bc_text_2">
                    Anéis de Concreto Lisos
                </li>
            </ul>
        </div>
        <div class="produto_title">Anel de Concreto Lisos</div>
        <div class="produto_text">
	  <p>
	    O Anel de Concreto Liso do Grupo Jesus de Mari seguem as normas da NBR contidas na ABNT, estes artefatos de concreto são utilizados na confecção de fossos sépticas e poços artesianos e são a garantia de uma obra segura.
	  </p>
        </div>
        <div class="produto_img">
            <img src="/images/img_aneis_de_concreto_1_mob.png">
        </div>
        <div class="produto_text">
        	Loren ipsun
        </div>
        <div class="produto_img">	
            <img src="/images/img_aneis_de_concreto_2_mob.png">
        </div>
    </div>
</div>
<div class="row">
	<div class="large-4 columns title_field">
    	<h1 class="title_text">Produtos</h1>
    </div>
	<div class="large-8 columns title_field">
    	<p class="text_title">
	  Nossa empresa disponibiliza a seus clientes uma ampla cartela de produtos relacionados a artefatos de concreto, incluindo Tubos de Concreto, Anéis de Concreto e Aduelas de Concreto todos produzidos pensando na mais alta qualidade de seus produtos e numa consciência ambiental no processo de confecção.
        </p>
    </div>    
</div>
<div class="row">
  <div class="large-12 columns content_desk">
    <% @categories.each do |category| %>
      <div class="large-4 columns box_category_desk">
	<%= link_to '', show_subcategory_product_path(category.id), :remote =>
true, :id => "cat_"+category.id.to_s, :class => category.css%>
      </div>
      <%end%>
  </div>
</div>
<!-- Exibe as Subcategorias -->
<div class="row subcat_desk">
  <div id="subcategory" class="large-12 columns" style="display:block;">
  </div>
</div>
<!-- Fim do menu de Subcategorias :( -->
<div class="row bg_row">
    <div id="products" class="large-6 small-12 columns content_desk">
      
    </div>
    <div id="product_desc" class="large-6 small-12 columns content_desk">
      
    </div>
</div>
<div class="row bg_row">
	<div id="subcategory_spec" class="large-12 columns content_desk">

 </div>
 </div>
<div class="row bg_row" id="product_spec">
    
</div>
<script type="text/javascript">
$('.box_category_desk').click(function(event) {
	$("div").children(".box_category_desk").removeClass('selected_box_category_desk');
	$(this).addClass('selected_box_category_desk');	   
  	
});
$('#cat_<%= @category_id.blank? ? @categories.first.id : @category_id.id%>').trigger('click');
</script>

app/views/products/show_product.js.erb
$('#products').html("<%=escape_javascript(render('product'))%>");
$('.item_category').css('cursor', 'pointer');

$('.item_category').click(function(event) {
	$(".field_item_category").children(".item_category").removeClass('selected_item_category');
	$(this).addClass('selected_item_category');
   
});

$('#prod_<%= @product_id.blank? ? @products.first.id : @subcategory_id.id%>').trigger('click');

app/views/products/show_productspec.js.erb
$('#product_desc').html("<%=escape_javascript(render('productspec'))%>");
$('#subcategory_spec').html("<%=escape_javascript(render('subcategoryspec'))%>");
$('#product_spec').html("<%=escape_javascript(render('productimagespec'))%>");

app/views/products/show_subcategory.js.erb
$('#subcategory').html("<%=escape_javascript(render('subcategory'))%>");
$('.sub_item_a').click(function(event) {
	$("#subcategory").children("a").removeClass('sub_item_a_selected');
	$(this).addClass('sub_item_a_selected');
   
});
$('#sub_<%= @subcategory_id.blank? ? @subcategories.first.id : @subcategory_id.id%>').trigger('click');

app/views/products/show_subcategoryspec.js.erb
$('#subcategory_spec').html("<%=escape_javascript(render('subcategoryspec'))%>");