config/routes.rb
KwJesusdemari::Application.routes.draw do

  get "treatment/index"

  get "group/index"
  
  resources :news
  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  resources :products do
    member do
      get "show_subcategory"
      get "show_product"
      get "show_productspec"
      get "show_subcategoryspec"
    end
  end
  resources :sustainability
  resources :budgets
  
  
  namespace(:admin){
    resources :categories do
      resources :subcategories do
        resources :products do
	  resources :product_images 
	end
      end
    end
    resources :notices
    resources :static_contents
    resources(:sections){
		resources :banners
    }
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  root :to => "home#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  











end

app/models/banner.rb
class Banner < ActiveRecord::Base
  #attr_accessible :title, :link, :section_id, :published, :active
  belongs_to :section
  has_attached_file:image, :styles =>{:thumb => "50x50#",:rotative => "950x410#",:partner => "378x295#",:partner_secondary => "378x160#",:group => "950x572#"}
end

app/models/budget.rb
class Budget < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  #attr_accessible :title, :description
has_many :subcategories
has_attached_file:logo, :styles =>{:thumb => "50x50#",:logo => "291x138#"}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name, :email, :phone, :city, :state, :message
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  validates_presence_of :title, :summary, :body
  has_attached_file:image, :styles =>{:thumb => "50x50#",:home => "150x100#",:index => "172x133#",:show => "172x133#"}
end

app/models/product.rb
class Product < ActiveRecord::Base
  #default_scope where(:active => true)
  #attr_accessible :summary, :body, :link, :active, :published
  belongs_to :subcategory
  has_many :product_images
  has_attached_file:logo, :styles =>{:thumb => "50x50>",:logo => "291x138>"}
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image, :styles => { :medium => "298x373>", :thumb => "150x150>"}
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/section.rb
class Section < ActiveRecord::Base
  #attr_accessible :title
  has_many :banners
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  #attr_accessible :category_id, :title
  belongs_to :category
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "inadmin"
  
  def index
    @users = User.all.paginate :page => params[:page],:per_page => 20
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to admin_user_path(@user), :notice  => "Dados Atualizados com sucesso!"
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, :notice => "Usuário Deletado com sucesso!"
  end
  
  def search
    if !params[:keyword].blank?
      @Results = User.search_for(params[:keyword]).paginate :page => params[:page],:per_page => 20
    end
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if !@user.update_attributes(params[:user])
      @user.errors
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/treatment_helper.rb
module TreatmentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
    <div id="Box_register_form" class="twelve columns">
		
		<%= form_for [:admin, @user] do |f| %>
		<div class="field">
			<%= f.label :name, "Nome" %>
			<%= f.text_field :name, :placeholder => "Nome" %>
		</div>
		<div class="field">
			<%= f.label :last_name, "Sobrenome" %>
			<%= f.text_field :last_name, :placeholder => "Sobrenome" %>
		</div>
		<div class="field">
			<%= f.label :email, "E-mail" %>
			<%= f.text_field :email, :placeholder => "E-mail" %>
		</div>
		<div class="field">
			<%= f.label :password, "Senha" %>
			<%= f.password_field :password, :placeholder => "Senha" %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation, "Confirmar Senha" %>
			<%= f.password_field :password_confirmation, :placeholder => "Confirme sua senha" %>
		</div>		
		<div id="Box_register_form_regras">
		  <h1>Regras</h1>
		  <p>
			<%= f.radio_button :role, :admin%>Administrador<br/>
			<%= f.radio_button :role, :supervisor %>Supervisor<br/>
			<%= f.radio_button :role, :user %>Usuário<br/>
		  </p>
		</div>
		
  		<p><%= f.submit "Salvar", :class => "button" %></p>
		<%end%>
	</div>

app/views/admin/users/edit.html.erb
<% 
	content_for :title do "Editar Usuário" end
%>
<%content_for :head do%>
	<%=stylesheet_link_tag "cadastro"%>
	<%= stylesheet_link_tag "admin_user"%>
<%end%>

<h1>Editar Usuário</h1>
<br />

<%= render 'form' %>

app/views/admin/users/index.html.erb
<% 
	content_for :title do "Usuários" end
%>
<h1>Usuários</h1>
<br />

<div id="name" class="twelve columns">
	<%=link_to "Novo usuário", new_admin_user_path, :class => "button", :style => "float:right;" %>
</div>

<div id="search" class="twelve columns">
<p>Informe o nome, sobrenome ou e-mail do usuário.</p>
	<%=form_tag '/admin/users/search', :method => :get, :name=>"formkeyword"%>
		<%=text_field_tag :keyword, nil %>
		<%=submit_tag "Buscar", :class => "button secondary"%>
	</form>
</div>

<table class="twelve columns">
  <tr>
    <th>Nome</th>
    <th>Sobrenome</th>
	<th>Email</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email%></td>
      <td><%= link_to "Show", admin_user_path(user) %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @users %>

<script>
	document.getElementById('keyword').focus();
</script>

app/views/admin/users/new.html.erb
<%content_for :head do%>
	<%=stylesheet_link_tag "cadastro"%>
<%end%>
<% title "Cadastro" %>
<h1>Editar Usuário</h1>

<%= render 'form' %>

app/views/admin/users/search.html.erb
<% 
	content_for :title do "Resultado da Busca por: #{params[:keyword]}" end
%>

<h1>Buscando por: <%=params[:keyword]%></h1>
<br />

<table>
  <tr>
    <th width="200px">Nome</th>
    <th width="200px">Sobrenome</th>
	<th width="200px">Email</th>
  </tr>
  	<%@Results.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email%></td>
      <td><%= link_to "Show", admin_user_path(user) %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<br><br>
<%=link_to "Voltar", admin_users_path, :class => "button"%>

app/views/admin/users/show.html.erb
<% 
	content_for :title do "Dados do Usuario" end
%>

<h1>Mostrar Usuário</h1>


<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Sobrenome:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>
<p>
  <%= link_to "Edit", edit_admin_user_path(@user), :class => "button secondary" %>
  <%= link_to "Destroy", admin_user_path(@user), :class => "button secondary", :confirm => 'Are you sure?', :method => :delete %>
  <%= link_to "View All", admin_users_path, :class => "button secondary" %>
</p>