config/routes.rb
KwJesusdemari::Application.routes.draw do

  get "treatment/index"

  get "group/index"
  
  resources :news
  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  resources :contacts
  resources :products do
    member do
      get "show_subcategory"
      get "show_product"
      get "show_productspec"
      get "show_subcategoryspec"
    end
  end
  resources :sustainability
  resources :budgets
  
  
  namespace(:admin){
    resources :categories do
      resources :subcategories do
        resources :products do
	  resources :product_images 
	end
      end
    end
    resources :notices
    resources :static_contents
    resources(:sections){
		resources :banners
    }
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  root :to => "home#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  











end

app/models/banner.rb
class Banner < ActiveRecord::Base
  #attr_accessible :title, :link, :section_id, :published, :active
  belongs_to :section
  has_attached_file:image, :styles =>{:thumb => "50x50#",:rotative => "950x410#",:partner => "378x295#",:partner_secondary => "378x160#",:group => "950x572#"}
end

app/models/budget.rb
class Budget < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  #attr_accessible :title, :description
has_many :subcategories
has_attached_file:logo, :styles =>{:thumb => "50x50#",:logo => "291x138#"}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :name, :email, :phone, :city, :state, :message
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  validates_presence_of :title, :summary, :body
  has_attached_file:image, :styles =>{:thumb => "50x50#",:home => "150x100#",:index => "172x133#",:show => "172x133#"}
end

app/models/product.rb
class Product < ActiveRecord::Base
  #default_scope where(:active => true)
  #attr_accessible :summary, :body, :link, :active, :published
  belongs_to :subcategory
  has_many :product_images
  has_attached_file:logo, :styles =>{:thumb => "50x50>",:logo => "291x138>"}
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image, :styles => { :medium => "298x373>", :thumb => "150x150>"}
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/section.rb
class Section < ActiveRecord::Base
  #attr_accessible :title
  has_many :banners
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  #attr_accessible :category_id, :title
  belongs_to :category
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController
  layout "inadmin"
  
  def index
    @notices = Notice.all
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(params[:notice])
    if @notice.save
      redirect_to admin_notices_path, :notice => "Successfully created notice."
    else
      render :action => 'new'
    end
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def update
    @notice = Notice.find(params[:id])
    if @notice.update_attributes(params[:notice])
      redirect_to [:admin, @notice], :notice  => "Successfully updated notice."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy
    redirect_to admin_notices_url, :notice => "Successfully destroyed notice."
  end
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/notices/_form.html.erb
<%= form_for ([:admin, @notice], :html => { :multipart => :true }) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title, "Titulo" %>
    <%= f.text_field :title, :placeholder => "Título", :class => "twelve columns" %>
  </p>
  <p>
    <%= f.label :summary, "Resumo" %>
    <%= f.text_field :summary, :placeholder => "Resumo", :class => "twelve columns"  %>
  </p>
  <p>
    <%= f.label :body, "Conteúdo" %>
    <%= f.text_area :body, :placeholder => "Conteúdo", :class => "twelve columns"  %>
  </p>
  <%if @notice.image.file?%>

  <p> 

  <%= image_tag(@notice.image.url(:thumb)) %>

  </p>
<% end %>
  <p>
    <%= f.label :image, "Imagem" %> 
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :published, "Publicada" %>
    <%= f.check_box :published %>
  </p>
  <p>
    <%= f.label :active, "Ativa" %>
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit "Salvar", :class => "button" %></p>
<% end %>

app/views/admin/notices/edit.html.erb
<% title "Editar Notícia" %>
<h1>Notícias - Editar <%= @notice.title %> </h1>
<%= render 'form' %>

<p>
  <%= link_to "Visualizar", [:admin, @notice], :class => "secondary small button" %> |
  <%= link_to "Ver Todas", admin_notices_path, :class => "secondary small button" %>
</p>

app/views/admin/notices/index.html.erb
<% title "Notícias" %>
<h1>Notícias</h1>

<p><%= link_to "+ Notícia", new_admin_notice_path, :class => "button" %></p>
  
<% for notice in @notices %>
<table class="twelve columns">
    <tr>
      <td>Título</td>
      <td><%= notice.title %></td>
    </tr>
    <tr>
      <td>Resumo</td>
      <td><%= notice.summary %></td>
    </tr>
    <tr>
      <td>Conteúdo</td>
      <td><%= notice.body %></td>
    </tr>
    <tr>
      <td>Publicada</td>
      <td><%= notice.published %></td>
    </tr>
    <tr>
      <td>Ativa</td>
      <td><%= notice.active %></td>
    </tr>
    <tr>
      <td>
      <%= link_to "Visualizar", [:admin, notice], :class => "secondary small button" %>
      <%= link_to "Editar", edit_admin_notice_path(notice), :class => "secondary small button" %>
      <%= link_to "Deletar", [:admin, notice], :confirm => 'Are you sure?', :method => :delete, :class => "secondary small button" %>
      </td>
    </tr>
</table>
<% end %>

<p><%= link_to "+ Notícia", new_admin_notice_path, :class => "button" %></p>

app/views/admin/notices/new.html.erb
<% title "New Admin/Notice" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_notices_path, :class => "secondary small button" %></p>

app/views/admin/notices/show.html.erb
<% title "Admin/Notice" %>
<h1>Notícias - <%= @notice.title %> </h1>

<p>
  <strong>Resumo:</strong>
  <%= @notice.summary %>
</p>
<p>
  <strong>Conteúdo:</strong>
  <%= @notice.body %>
</p>
<p>
  <strong>Imagem:</strong>
  <%= image_tag(@notice.image.url(:thumb)) %>
</p>
<p>
  <strong>Publicada:</strong>
  <%= @notice.published %>
</p>
<p>
  <strong>Ativa:</strong>
  <%= @notice.active %>
</p>

<p>
  <%= link_to "Editar", edit_admin_notice_path(@notice), :class => "secondary small button" %> 
  <%= link_to "Deletar", [:admin, @notice], :confirm => 'Are you sure?', :method => :delete, :class => "secondary small button" %> 
  <%= link_to "Ver todas", admin_notices_path, :class => "secondary small button" %>
</p>